In [1]:
import numpy as np

A = np.arange(2,14).reshape((3,4))
print(A)
print('-------------------------')
print(A[1]) #輸出第1“行”＃
print('-------------------------')
print(A[2][3])
print('-------------------------')
print(A[2,3])
print('-------------------------')
print(A[2,:])
print('-------------------------')
print(A[1,1:3])

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
-------------------------
[6 7 8 9]
-------------------------
13
-------------------------
13
-------------------------
[10 11 12 13]
-------------------------
[7 8]


In [2]:
# 矩陣的迴圈（行）

for row in A:
    print(row)
    print('-------------------------')

[2 3 4 5]
-------------------------
[6 7 8 9]
-------------------------
[10 11 12 13]
-------------------------


In [3]:
# 矩陣的迴圈（列）

for column in A.T:  #為了迭代“列”，先用A.T將行列翻轉在迭代＃
    print(column)
    print('-------------------------')

[ 2  6 10]
-------------------------
[ 3  7 11]
-------------------------
[ 4  8 12]
-------------------------
[ 5  9 13]
-------------------------


In [16]:
A_flat = A.flatten() #先將矩陣打散,flat輸出是個object＃
print(A_flat)
for item in A.flat:
    print(item)

[ 2  3  4  5  6  7  8  9 10 11 12 13]
2
3
4
5
6
7
8
9
10
11
12
13
