In [20]:
import numpy as np

#numpy的合併

A = np.array([1,1,1])
B = np.array([2,2,2])

C = np.vstack((A,B)) # vertical stack 直的合併
print(C)
D = np.hstack((A,B)) # horizontal stack 橫的合併
print(D)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [21]:
print(A.shape) #沒有行沒有列，單純三個值(一維矩陣)
print(A.ndim)
print(A[:,np.newaxis]) #產生列
print(A[:,np.newaxis].shape)
print(A[np.newaxis,:]) #產生行
print(A[np.newaxis,:].shape)

(3,)
1
[[1]
 [1]
 [1]]
(3, 1)
[[1 1 1]]
(1, 3)


In [22]:
A_2 = A[np.newaxis,:] #加入行，因為本來是一維矩陣，會無法二維矩陣的合併
B_2 = B[np.newaxis,:]
E = np.concatenate((A_2,B_2,A_2,B_2)) #預設axis=0
print(E)
F = np.concatenate((A_2,B_2,A_2,B_2),axis=1)
print(F)

[[1 1 1]
 [2 2 2]
 [1 1 1]
 [2 2 2]]
[[1 1 1 2 2 2 1 1 1 2 2 2]]


In [23]:
# numpy的分割

In [26]:
AA = np.arange(12).reshape((3,4))
print(AA)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
AA1 = np.split(AA,2,axis=1) #把行切開，所以是直刀
print(AA1)
AA2 = np.split(AA,1) #把列切開，所以是橫刀，預設axis=0
print(AA2)
AA3 = np.array_split(AA,3,axis=1) #不等份分割（無法整除的分割）
print(AA3)

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [38]:
print(np.vsplit(AA,3)) 
print(np.hsplit(AA,2))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
