In [17]:
import numpy as np

x1 = np.array([[1,2,3],
              [4,5,6]], float)/ (10*np.pi)   
seq = np.sin(x1)
res = np.cos(x1)
print(seq)
#sin週期是2pi = 2*3.14 = 6.28 當pi = 3.14時趨近0,        pi/2= 1.57時接近最大值1, 3pi/2 = 4.71時接近最小值-1
print('-----------------')
print(res)
#cos週期是2pi = 2*3.14 = 6.28 當pi = 3.14時接近最小值-1,  pi/2= 1.57時趨近0,      3pi/2 = 4.71時趨近0,      2pi時接近最大值1

print('-----------------')

x2 = x1[:, :, np.newaxis]
x3 = x1[np.newaxis, :, :]

print(x1.shape)
print('-----------------')
print(x2)
print(x2.shape)
print('-----------------')
print(x3)
print(x3.shape)


[[ 0.03182561  0.06361898  0.0953479 ]
 [ 0.12698022  0.15848389  0.18982699]]
-----------------
[[ 0.99949344  0.99797426  0.99544401]
 [ 0.99190525  0.98736156  0.98181756]]
-----------------
(2, 3)
-----------------
[[[ 0.03183099]
  [ 0.06366198]
  [ 0.09549297]]

 [[ 0.12732395]
  [ 0.15915494]
  [ 0.19098593]]]
(2, 3, 1)
-----------------
[[[ 0.03183099  0.06366198  0.09549297]
  [ 0.12732395  0.15915494  0.19098593]]]
(1, 2, 3)


In [26]:
import matplotlib.pyplot as plt
print(seq[0, :]) 
print(res[0, :])


[ 0.03182561  0.06361898  0.0953479 ]
[ 0.99949344  0.99797426  0.99544401]
