In [ ]:
import numpy as np
array = np.array([[1,2,3],[3,4,5]])
print(array)
print('number of dim:',array.ndim)  #查詢維度＃
print('shape:',array.shape) #行，列各是多少＃
print('size:',array.size) 

In [4]:
a = np.array([55,63,75],dtype=np.int)
print(a)
print(a.dtype)

[55 63 75]
int64


In [6]:
zero = np.zeros((3,3))
print(zero)
one = np.ones((4,4))
print(one)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [10]:
r = np.arange(20).reshape((4,5))
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [12]:
l = np.linspace(1,6,4) #一段“起始”到“結束-1”之中切“幾段”＃
lrs = np.linspace(1,6,4).reshape(2,2)
print(l)
print(lrs)

[ 1.          2.66666667  4.33333333  6.        ]
[[ 1.          2.66666667]
 [ 4.33333333  6.        ]]


In [25]:
b = np.array([[1,2],
              [2,3]])
c = np.arange(4).reshape((2,2))

d = b*c
print(d)
d_dot = np.dot(b,c)
d_dot_2 = b.dot(c)   #意義ㄧ樣 不同表示＃
print(d_dot)
print(d_dot_2)

[[0 2]
 [4 9]]
[[ 4  7]
 [ 6 11]]
[[ 4  7]
 [ 6 11]]


In [24]:
r = np.random.random((2,4))
print(r)
print(np.sum(r))
print(np.min(r))
print(np.max(r))
print(np.sum(r,axis=0)) #各”列“總和＃
print(np.min(r,axis=1)) #各“行”找最小值＃
print(np.max(r,axis=1)) #各“行”找最大值＃

[[ 0.21452188  0.20153535  0.02131264  0.84691527]
 [ 0.85860429  0.70681517  0.19088426  0.47168606]]
3.51227492113
0.021312637296
0.858604291709
[ 1.07312617  0.90835052  0.2121969   1.31860132]
[ 0.02131264  0.19088426]
[ 0.84691527  0.85860429]


In [38]:
A = np.arange(2,14).reshape((3,4))
print(A)
print(np.argmin(A)) #最小值的索引位置＃
print(np.argmax(A))
print(np.median(A)) #中位數＃
print(np.mean(A)) #總平均值＃

print(np.cumsum(A)) #每個索引位置成為前面所有索引位置累加值#
print(np.diff(A)) #矩陣值為跟前一個索引值的差＃

print(np.transpose(A)) #行列位置交換＃ #常用＃
print(A.T)

print(np.clip(A,5,9)) #A矩陣中，低於五都變成五，高於九都變成九＃


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
